.\" Copyright (C) 2017 Graeme Walker
.\" 
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\" Copyright (C) 2017 Graeme Walker
.TH videotools 1 "" "" "User Commands"
.SH NAME
VideoTools \- a set of programs for managing video streams from webcams and surveillance cameras
.SH SYNOPSIS
.SY
.B vt-alarm
[\f...\fR]
.YS
.SY
.B vt-channel
[\f...\fR]
.YS
.SY
.B vt-maskeditor
[\f...\fR]
.YS
.SY
.B vt-fileplayer
[\f...\fR]
.YS
.SY
.B vt-httpclient
[\f...\fR]
.YS
.SY
.B vt-httpserver
[\f...\fR]
.YS
.SY
.B vt-recorder
[\f...\fR]
.YS
.SY
.B vt-rtpserver
[\f...\fR]
.YS
.SY
.B vt-rtspclient
[\f...\fR]
.YS
.SY
.B vt-socket
[\f...\fR]
.YS
.SY
.B vt-viewer
[\f...\fR]
.YS
.SY
.B vt-watcher
[\f...\fR]
.YS
.SY
.B vt-webcamserver
[\f...\fR]
.YS
.SY
.B vt-webcamplayer
[\f...\fR]
.YS
.SH DESCRIPTION
A set of programs for managing video streams from webcams and surveillance cameras.
.PP
.SH COPYRIGHT
Copyright (C) 2017 Graeme Walker
.PP
This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
